In [3]:
import nltk
import re
from nltk.corpus import stopwords

In [4]:
import pandas as pd
import numpy as np

In [5]:
cd D:\Downloads\emotion_kaggle

D:\Downloads\emotion_kaggle


In [6]:
train_text=pd.read_csv("train.txt",header=None,index_col=False,names=['text'])
test_text=pd.read_csv('test.txt',header=None,index_col=False,names=['text'])
val_text=pd.read_csv("val.txt",header=None,index_col=False,names=['text'])

In [7]:
train_text['text']=train_text['text'].str.split(";")
val_text['text']=val_text['text'].str.split(";")
test_text['text']=test_text['text'].str.split(";")

In [8]:
train_text

text
0                     [i didnt feel humiliated, sadness]
1      [i can go from feeling so hopeless to so damne...
2      [im grabbing a minute to post i feel greedy wr...
3      [i am ever feeling nostalgic about the firepla...
4                          [i am feeling grouchy, anger]
...                                                  ...
15995  [i just had a very brief time in the beanbag a...
15996  [i am now turning and i feel pathetic that i a...
15997              [i feel strong and good overall, joy]
15998  [i feel like this was such a rude comment and ...
15999  [i know a lot but i feel so stupid because i c...

[16000 rows x 1 columns]

In [9]:
from tensorflow.keras.preprocessing.text import one_hot
from nltk.stem import PorterStemmer, WordNetLemmatizer
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vivek\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [11]:
train_text['emotion']=train_text['text'].str[1]
train_text['text']=train_text['text'].str[0]
len(train_text['emotion'].unique())

6

In [10]:
val_text['emotion']=val_text['text'].str[1]
val_text['text']=val_text['text'].str[0]
val_text

text  emotion
0     im feeling quite sad and sorry for myself but ...  sadness
1     i feel like i am still looking at a blank canv...  sadness
2                        i feel like a faithful servant     love
3                     i am just feeling cranky and blue    anger
4     i can have for a treat or if i am feeling festive      joy
...                                                 ...      ...
1995  im having ssa examination tomorrow in the morn...  sadness
1996  i constantly worry about their fight against n...      joy
1997  i feel its important to share this info for th...      joy
1998  i truly feel that if you are passionate enough...      joy
1999  i feel like i just wanna buy any cute make up ...      joy

[2000 rows x 2 columns]

In [11]:
test_text['emotion']=test_text['text'].str[1]
test_text['text']=test_text['text'].str[0]
test_text

text  emotion
0     im feeling rather rotten so im not very ambiti...  sadness
1             im updating my blog because i feel shitty  sadness
2     i never make her separate from me because i do...  sadness
3     i left with my bouquet of red and yellow tulip...      joy
4       i was feeling a little vain when i did this one  sadness
...                                                 ...      ...
1995  i just keep feeling like someone is being unki...    anger
1996  im feeling a little cranky negative after this...    anger
1997  i feel that i am useful to my people and that ...      joy
1998  im feeling more comfortable with derby i feel ...      joy
1999  i feel all weird when i have to meet w people ...     fear

[2000 rows x 2 columns]

In [12]:
final_text=[]
ps=PorterStemmer()
for i in range(len(train_text)):
    review=re.sub('[^a-zA-Z]',' ',train_text['text'][i])
    review=re.split(' ',review)
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    final_text.append(review)
    

In [13]:
finalval_text=[]
ps=PorterStemmer()
for i in range(len(val_text)):
    review=re.sub('[^a-zA-Z]',' ',val_text['text'][i])
    review=re.split(' ',review)
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    finalval_text.append(review)

In [14]:
finaltest_text=[]
ps=PorterStemmer()
for i in range(len(test_text)):
    review=re.sub('[^a-zA-Z]',' ',test_text['text'][i])
    review=re.split(' ',review)
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    finaltest_text.append(review)

In [15]:
train_text['final_text']=final_text
test_text['finaltest_text']=finaltest_text
val_text['finalval_text']=finalval_text

In [16]:
voc_size=10000
onehot_train=[one_hot(words,voc_size) for words in final_text]
print(onehot_train)

[[8305, 5153, 8461], [3978, 5153, 4195, 1778, 283, 5819, 8028, 1561, 7318], [181, 244, 5394, 912, 5153, 8320, 7570], [5007, 5153, 8206, 5154, 2418, 434, 8175], [5153, 7904], [7543, 5153, 63, 5842, 5422, 4716, 3035], [7543, 827, 3149, 5662, 2375, 4354, 7543, 2115, 6442, 849, 8098, 400, 5153, 1442, 774], [5153, 2448, 1280, 9995, 3508, 2398, 6866, 6924], [7581, 2398, 5153, 7581, 3121, 2188, 7465, 3137, 8219], [5153, 9825], [5153, 1442, 6601, 4738, 4568, 7122, 9261], [5153, 2604, 4899, 382, 7262, 4336, 2656, 7655], [8610, 4403, 5662, 2398, 5153, 8829], [5153, 1106, 7408, 579], [3517, 5759, 8341, 7776, 4442, 8832, 8800, 1760, 8617, 5662, 2335, 8446, 1280, 7652, 444, 9861, 5846, 7111, 6900, 5153, 63, 4857], [5153, 8016, 1761, 559], [8305, 6452, 5153, 5611], [5153, 2597, 1519, 5662], [7531, 5153, 9337, 17, 2473, 1569, 7511, 3948, 3269, 17, 2217], [5153, 8063, 8579, 958, 2615, 9296, 7847, 2915], [5153, 9637, 3509, 9486, 4902, 7518, 6370, 7518], [5153, 1114, 4462, 198, 2378, 7820, 5153, 7507, 5

In [17]:
onehot_test=[one_hot(words,voc_size) for words in finaltest_text]
onehot_val=[one_hot(words,voc_size) for words in finalval_text]

In [18]:
sent_length=20
embedded_docs_train=pad_sequences(onehot_train,padding='pre',maxlen=sent_length)
print(embedded_docs_train)

[[   0    0    0 ... 8305 5153 8461]
 [   0    0    0 ... 8028 1561 7318]
 [   0    0    0 ... 5153 8320 7570]
 ...
 [   0    0    0 ... 2229 7809 8662]
 [   0    0    0 ... 7824  181 6287]
 [   0    0    0 ... 5153 7496 8307]]


In [19]:
sent_length=20
embedded_docs_test=pad_sequences(onehot_test,padding='pre',maxlen=sent_length)
embedded_docs_val=pad_sequences(onehot_val,padding='pre',maxlen=sent_length)

In [98]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM
embedding_vector_features=300
model=Sequential()
model.add(Embedding(voc_size,300,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(6,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [96]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')


In [63]:
X_train=embedded_docs_train.astype(np.float32)
X_test=embedded_docs_test.astype(np.float32)
X_val=embedded_docs_val.astype(np.float32)

In [70]:
Y_train=pd.DataFrame(ohe.fit_transform(train_text)).iloc[:,:-2].values.astype(np.float32)
Y_test=pd.DataFrame(ohe.fit_transform(test_text)).iloc[:,:-2].values.astype(np.float32)
Y_val=pd.DataFrame(ohe.fit_transform(val_text)).iloc[:,:-2].values.astype(np.float32)

In [71]:
Y_train

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)

In [99]:
model.fit(X_train,Y_train, batch_size=128, epochs=5, validation_data=(X_val, Y_val))

Epoch 1/5
125/125 [==============================] - 14s 97ms/step - loss: 1.2476 - accuracy: 0.5340 - val_loss: 0.6414 - val_accuracy: 0.7770
Epoch 2/5
125/125 [==============================] - 12s 97ms/step - loss: 0.3742 - accuracy: 0.8693 - val_loss: 0.3862 - val_accuracy: 0.8605
Epoch 3/5
125/125 [==============================] - 12s 95ms/step - loss: 0.1946 - accuracy: 0.9297 - val_loss: 0.3635 - val_accuracy: 0.8725
Epoch 4/5
125/125 [==============================] - 12s 93ms/step - loss: 0.1296 - accuracy: 0.9528 - val_loss: 0.4134 - val_accuracy: 0.8640
Epoch 5/5
125/125 [==============================] - 12s 94ms/step - loss: 0.0996 - accuracy: 0.9638 - val_loss: 0.4391 - val_accuracy: 0.8705


In [100]:
pred=model.predict(X_test)
pred=pred.argmax(axis=-1)
predl=np.zeros((Y_test.shape))
for i in range(len(pred)):
    predl[i][pred[i]]=1
predl

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [101]:
from sklearn.metrics import accuracy_score
score=accuracy_score(Y_test,predl)
score

0.856